# Generated by Django 4.2.7 on 2024-03-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0004_visitingcard_alter_useraccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitingcard',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
