# Generated by Django 4.2.7 on 2024-03-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0005_alter_visitingcard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitingcard',
            name='website',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
